version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=TRYBE_TASK_LIST
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    restart: 'always'
